### PR TITLE
Update low res logos on /download/iot page

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Updated logos for:
- Artik
- Intel JOULE
- Raspberry Pi
- Snapdragon
- Tank
- Up2

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/download/iot](http://0.0.0.0:8001/download/iot)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure the logos listed above aren't of low resolution.

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1098

### CODE REVIEW

**Comment by kwm14** [comment]
@sowasred2012 list of logo updates look good 👍 but from review 'Intel Joule' looks pixelated and from inspection, it's a PNG which is probably the reason why.

I've created a new asset so it's in SVG format so will be crisp 😉 if you could update this logo that would be great.

Intel Joule - https://assets.ubuntu.com/v1/db101789-intel-joule.svg

**Comment by sowasred2012** [comment]
> @sowasred2012 list of logo updates look good 👍 but from review 'Intel Joule' looks pixelated and from inspection, it's a PNG which is probably the reason why.
> 
> I've created a new asset so it's in SVG format so will be crisp 😉 if you could update this logo that would be great.
> 
> Intel Joule - https://assets.ubuntu.com/v1/db101789-intel-joule.svg

Will do, thanks!

**Comment by kwm14** [comment]
@sowasred2012 Thanks. Design LGTM 👍

**Comment by solazio** [comment]
@sowasred2012 the link to the issue that this PR is fixing is wrong. In these case please add the link to the issue https://github.com/canonical-web-and-design/web-squad/issues/1098

**Pull request merged**
