### PR TITLE
5117 improve IoT template

### LINKED ISSUE #5117: /blog integration:  Improve the template blog/internet-of-things
## Summary
The  ` blog/internet-of-things` template should resemble https://blog.ubuntu.com/internet-of-things

### LINKED ISSUE #5121: /blog integration: Add navigation
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Add the blog navigation to get to the different groups.
**Dropdowns** on the navigation to select the categories are no longer needed when we integrate the filtering on the pages
## Screenshot

u.c/Screenshot%20from%202019-05-09%2013-51-39.png
image

### PR DESCRIPTION
**Pull request by solazio**
## Done

Improved blog/internet-of-things
Add navigation
Add template pagination

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/blog/internet-of-things](http://0.0.0.0:8001/blog/internet-of-things)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Make sure the page looks similar to [https://blog.ubuntu.com/internet-of-things](https://blog.ubuntu.com/internet-of-things)
- Make sure the filters work
- Make sure the pagination works

## Issue / Card

Fixes #5117 
Fixes #5121

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] navigation: the word "Things" should be capitalised - Internet of Things
Ubuntu (1)

**Comment by anasereijo** [comment]
If you filter by White papers you can see an Article. Can you please hide it ?

Ubuntu (2)

**Comment by solazio** [comment]
@anasereijo I fixed the navigation with capitalised words. For the filters, it behaves exactly the same as https://blog.ubuntu.com/internet-of-things?category=white-papers#posts-list. We could force it to change and display whitepaper instead of article, however I don't think that is the right way to go. We need to discuss it with @pmahnke and @anthonydillon next week.
image

**Comment by anasereijo** [comment]
Hi @solazio 

don't capitalise the word 'centre' as it's not a product or a name.

Regarding the article appearing in white papers filter that's fine, you can sort that out with @anthonydillon when he's back

**Comment by deadlight** [comment]
The pagination styling is broken, the dots are meant to be in the middle:
image

Not sure if this bug is related to your changes but it's not present on live.

**Comment by solazio** [comment]
@deadlight well spotted. I will look into it.

**Comment by deadlight** [comment]
@solazio also there's no page title - it's just showing as "| ubuntu"

**Comment by solazio** [comment]
@deadlight I fixed the title issue and also added description. For the pagination problem I opened a [new issue](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5148).

**Pull request merged**
