### PR TITLE
5130 implement blog archive

### LINKED ISSUE #5130: /blog: Implement archive template
# Summary

The blog module version **1.5.4** now supports the archive.

To use this create the `blog/archives.html` template. All data will be available in it. 

Use https://blog.ubuntu.com/archives as a guideline

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Implemented blog/archives template

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/blog/archives](http://0.0.0.0:8001/blog/archives)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure the page looks and behaves similarly to https://blog.ubuntu.com/archives
- Ensure the heading changes appropriately when a group filter is applied: http://0.0.0.0:8001/blog/archivesblog/archives?group=canonical-announcements

## Issue / Card

Fixes #5130

### CODE REVIEW

**Comment by solazio** [comment]
@sowasred2012 there is a problem with the dots between the months. They are meant to be in the middle, not at the bottom. Anyway, we have the same issue with the pagination and I created an issue for this and hopefully when we fix the pagination this will be fixed as well. https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5148

image

**Comment by anasereijo** [comment]
@sowasred2012 looking good just a couple of things:

- [ ] can you keep the header grey like we [currently](https://blog.ubuntu.com/archives) have?

- [ ] I think we should keep the blog navigation even though there is no link on the nav for archive.

- [ ] check pagination as per @solazio comment

**Comment by sowasred2012** [comment]
> * [ ]  check pagination as per @solazio comment

@anasereijo no problem - I've updated with your first two points, and this pagination issue will be resolved when we resolve #5148

**Comment by anasereijo** [comment]
lgtm :)

**Pull request merged**
