### PR TITLE
Add /blog/upcoming page

### LINKED ISSUE #5136: /blog: Implement upcoming page
## Summary

Implement the upcoming page as on https://blog.ubuntu.com/upcoming

Use the template `blog/upcoming.html`

### PR DESCRIPTION
**Pull request by solazio**
## Done

Add /blog/upcoming page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/blog/upcoming](http://0.0.0.0:8001/blog/upcoming)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Make sure it looks and behaves the same as https://blog.ubuntu.com/upcoming

## Issue / Card

Fixes #5136

### CODE REVIEW

**Comment by anasereijo** [comment]
I didn't know we have this page. How people get there?
Also, the link isn't very 'nice' so I wonder if we can call it something else? Or if we need this page at all? @pmahnke @anthonydillon any thoughts?

**Comment by sowasred2012** [comment]
This looks spot on, but I wonder whether the cards here and the cards on https://blog.ubuntu.com/ in the upcoming section should be consistent - one presents the date as though it were when the post was published ("by Canonical on 11 February 2019"), and the other presents it as the date of the event ("11 February 2019")

- /blog/upcoming
Screenshot 2019-05-28 at 16 05 05

- blog.ubuntu.com
Screenshot 2019-05-28 at 16 03 51

**Comment by anasereijo** [comment]
@anthonydillon have you seen my comment?

**Comment by anthonydillon** [comment]
@anasereijo I can't find where this page was requested. Maybe @pmahnke knows?

**Comment by anasereijo** [comment]
hey @solazio 

- [ ] I agree with @sowasred2012. The cards should show the date of the event and not when it was published. 
- [ ] change this page title to Events and webinars
- [ ] match the hero with the one we have on /archives page: `class="p-strip--accent is-dark is-deep"`

**other changes:**
Not sure if @sowasred2012 is going to make the following changes or if it's you? maybe check with him:
- [ ] 'upcoming events and webinars' section on the homepage is currently linking to the archives page and it should be linking to this one.
- [ ] change that section name to 'Events and webinars'.

**Comment by anasereijo** [comment]
@pmahnke should we change the URL now? or should we keep it like this and once it's live we can discuss this with Marketing?

**Comment by anasereijo** [comment]
@solazio looks good design wise 👍

**Pull request merged**
