### PR TITLE
Example for upgrade guide: Correct markup structure (grid and centering utilities)

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Example of how to correctly order grid classes and align / vertically center utilities so they don't interfere with each other.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Find strip containing "The number one platform for containers"
- Ensure it works as expected.

### CODE REVIEW

**Comment by anthonydillon** [comment]
@lyubomir-popov is this to be reviewed or just an example?

**Comment by lyubomir-popov** [comment]
@anthonydillon Both. It needs to go into the feature branch, but since there are numerous instances of this kind of issue, I've put a link to this PR in the 2.0 migration guide.

**Comment by lyubomir-popov** [comment]
@anthonydillon can you review please

**Comment by anthonydillon** [comment]
@lyubomir-popov could you please fix up the sections on the homepage as an example. Its not great to have the page left in a half broken state.

**Comment by lyubomir-popov** [comment]
@anthonydillon sure, can I do in a separate pr though? I want this to be as small as possible because it is linked to form the upgrade guide.

**Pull request merged**
