### PR TITLE
Promote multipass run

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Promoted multipass.run in the following places:
- /download
- /download/server
- Developer menu
- Download menu

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Go to /download and check it matched the [copy doc](https://docs.google.com/document/d/1egsCcmFiz8czeHsvwoB9Jz815Ij5Urtf7Ngrru6Zd4o/edit#heading=h.uabbhljvifoy)
- Go to /download/server and check it matched the [copy doc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit#)
- Open the developer menu and check it matched the [copy doc](https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit)
- Open the download menu and check it matched the [copy doc](https://docs.google.com/document/d/11pX5gxOE6UWljIGRBZdwuCL1MHzs4pNgxJpK0mcIqdQ/edit)

### CODE REVIEW

**Comment by pmahnke** [comment]
@anthonydillon I don't like how the /download/server has changed... I would prefer to add in multipass, but leave the horiztonal 18.04 and 19.04 cards, I think the priority is wrong otherwise... I think this is a UX too far.

**Comment by anasereijo** [comment]
**/download** 👍  LGTM
**/download/server**
  I agree with @pmahnke. I suggest leaving the cards as we currently have - 12 col (can we remove the shadows? I never liked that) on the multipass card please try to put the button on the right side to keep consistency.
**Developer menu**👍  LGTM
**Download menu**👍  LGTM

**Comment by anthonydillon** [comment]
@anasereijo @pmahnke done, ready for another review

**Comment by anthonydillon** [comment]
Closing as this has all changed

**Pull request closed without merging**
