### PR TITLE
Updated /download/iot page 

### LINKED ISSUE #4954: [iot] update /download/iot page
[copy doc](https://drive.google.com/open?id=1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ)

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Updated /download/iot page to focus on non-Core downloads to get people started

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/download/iot/](http://0.0.0.0:8001/download/iot)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Compare to the [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#)

## Issue / Card

Fixes #4954

### CODE REVIEW

**Comment by pmahnke** [comment]
@caldav can you take a look?

**Comment by anasereijo** [comment]
Desktop HD

**Comment by anasereijo** [comment]
@pmahnke I just had the design review meeting and this will need some more design work. I will upload the new version as soon it's ready.

**Comment by anasereijo** [comment]
design note: this can go live as it is now and will be amended later

**Pull request merged**
