### PR TITLE
Add SRC landing page

### PR DESCRIPTION
**Pull request by solazio**
## Done

Add SRC landing page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots](http://0.0.0.0:8001/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Make sure it complies with the [brief](https://docs.google.com/document/d/1xhjiRveHItibFEqhZJdG_FYbgYVhWmZG2LAXYyzkyCk/edit?ts=5ced4c72)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1162

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] the heading needs a background. please use the generic light-grey one.
- [ ]  can we have the green button on mobile?

**Comment by anasereijo** [comment]
@WendyS1000 please let us know once the copy is final

**Comment by anasereijo** [comment]
@caldav can you please have a look? thanks

**Comment by anasereijo** [comment]
Marketing just requested to have an image on the header. I'm trying to sort this out so for now it's a Design -1

**Comment by anasereijo** [comment]
@solazio use this image https://assets.ubuntu.com/v1/2d645bd4-robot03.svg

**Comment by anasereijo** [comment]
@WendyS1000 @caldav can you please have a look and check if everything is ok?

**Comment by WendyS1000** [comment]
Hi, @solazio and @anasereijo, thanks for this. 

1. Is the logo that has been used from the SRC's website? I don't recognise it from the case study PDF. Could we use one of their robot graphics from the PDF Instead? Please see 4th page of PDF (Solution heading) below: https://drive.google.com/drive/u/0/folders/1J94W8P2fiCM5oSRFEzRcoFDRFz_ycOOd   

2. Can we bring the H1 text to life by adding a background colour (something like this, https://www.ubuntu.com/engage/snap-deltas?utm_source=takeover&utm_medium=takeover&utm_campaign=CY19_IOT_UbuntuCore_Whitepaper_SnapDeltas_Takeover). 

Sorry about all the back and forth on this landing page. This is my first one, but I'll make sure to include header details in briefs going forward. 

Thanks!

**Comment by anasereijo** [comment]
Hi @WendyS1000,

 I did try to use SRC logo but the one I could find on Google is very low res as well as the images from the whitepaper. That's why I decided to use our branded robot. If you or Sarah could ask them directly to send an SVG logo that would be great for future use. Please let me know once you get the SVG logo and we can try to update this landing page sometime the future.

- [ ] @solazio plese change the background to `
transform: rotate(180deg);
background-image: linear-gradient(34deg, #E95420 0%, #C44631 6%, #A33940 12%, #8B304A 18%, #7C2B51 24%, #772953 29%, #55163B 51%, #370626 75%, #2C001E 89%);
`

- [ ]  @solazio because the background is now darker please use the [white version of the robot](https://assets.ubuntu.com/v1/39ebd977-robot.svg)

- [ ]  @solazio make the hero text white because of the new background colour

All these changes could be avoided if I have a design issue before developers start building it. @SirSamTumless maybe we should put design time on all landing pages from now on to avoid all these changes?

Thanks!

**Comment by SirSamTumless** [comment]
@anasereijo That makes sense! I will do it from now on when creating the issues.

**Comment by WendyS1000** [comment]
Hi, @solazio @anasereijo, and @SirSamTumless this is good to go live! I like the background colour! Thanks for all your help with this page. I will make sure to smooth out the process from my side, going forward.

**Comment by anasereijo** [comment]
@solazio please make the robot smaller: remove the `width="175"`

**Comment by WendyS1000** [comment]
Hi @SirSamTumless, please give me a shout when this is live, so we can do social media posting etc. Thanks!

**Comment by anasereijo** [comment]
@solazio looking good! can you push it live and let us know?(@SirSamTumless @WendyS1000 and I?

**Pull request merged**
