### PR TITLE
5029 lxd takeover and landing page

### LINKED ISSUE #5029: [WP: takeover + lp] LXD - Build
brief https://docs.google.com/document/d/1zR-aMuCZJJXlmRXBK-XG2AQ8iOf6T10hhnS8tBYqjsI/edit

### PR DESCRIPTION
**Pull request by solazio**
## Done

Add LXD takeover and landing page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) and [/engage/lxd-whitepaper](http://0.0.0.0:8001/engage/lxd-whitepaper)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Make sure it complies with the [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5027) and [more design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5029)
-Make sure it complies with the [brief](https://docs.google.com/document/d/1zR-aMuCZJJXlmRXBK-XG2AQ8iOf6T10hhnS8tBYqjsI/edit#) and [copydoc](https://docs.google.com/document/d/1gcCaCuOdNBV8pqajXVCdAAxOTmO22cdPRD1h5j3oRbU/edit )

## Issue / Card

[Fixes #5029](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5029)

### CODE REVIEW

**Comment by anasereijo** [comment]
@solazio there are a few copy changes requested by marketing. please check both briefs (takeover + landing page)

**Comment by anasereijo** [comment]
@Khutch25 can you have a look again please?

**Comment by Khutch25** [comment]
Two updates 
- The UTM is missing for the takeover - please update 'Download the whitepaper' link to "/engage/lxd-whitepaper?utm_source=Takeover&utm_campaign=CY19_DC_Containers_Whitepaper_LXD"
- in the landing page, the comma needs to be taken out after "explores" in the last paragraph

**Comment by solazio** [comment]
@Khutch25 please have another look. thanks

**Comment by Khutch25** [comment]
LGTM @solazio, thank you!

**Pull request merged**
